# Generated by Django 5.0.6 on 2024-07-07 14:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('day', models.CharField(blank=True, max_length=20)),
                ('login_time', models.TimeField(blank=True, null=True)),
                ('logout_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Half day', 'Half day'), ('Absent', 'Absent')], default='Present', max_length=10)),
                ('on_time_late', models.CharField(blank=True, choices=[('On Time', 'On Time'), ('Late', 'Late')], max_length=10, null=True)),
                ('regulation_reason', models.TextField(blank=True, null=True)),
                ('is_logged_in', models.BooleanField(default=False)),
                ('total_login_time_hours', models.IntegerField(default=0)),
                ('total_login_time_minutes', models.IntegerField(default=0)),
                ('total_break_time_hours', models.IntegerField(default=0)),
                ('total_break_time_minutes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BreakType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('company_gstin', models.CharField(max_length=15)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone_number', models.CharField(max_length=15)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('company_about', models.TextField(blank=True, null=True)),
                ('company_tagline', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('capital', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disposition', models.CharField(blank=True, choices=[('Fresh', 'Fresh'), ('Connected', 'Connected'), ('Not connected', 'Not connected')], default='Fresh', max_length=20, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('reminder', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('unique_invoice_number', models.CharField(max_length=8, unique=True)),
                ('amount_in_words', models.CharField(max_length=255)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='CallCenter_App.company')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='invoice_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='CallCenter_App.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='CallCenter_App.invoicepdf'),
        ),
        migrations.CreateModel(
            name='LeadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('performed_by', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='CallCenter_App.lead')),
            ],
        ),
        migrations.CreateModel(
            name='PaidCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('contact_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('payment_date', models.DateField()),
                ('package_start_date', models.DateField(default=django.utils.timezone.now)),
                ('package_end_date', models.DateField(blank=True, null=True)),
                ('transaction_id', models.CharField(max_length=100)),
                ('pan_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')])),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('amount_with_gst', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('verified', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=50)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_customers', to='CallCenter_App.lead')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_customers', to='CallCenter_App.package')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_customers', to='CallCenter_App.paymentmethod')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='CallCenter_App.paidcustomer'),
        ),
        migrations.AddField(
            model_name='lead',
            name='sub_disposition',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_dispositions', to='CallCenter_App.subdisposition'),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='CallCenter_App.team'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Team Leader', 'Team Leader'), ('Agent', 'Agent')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('On Resign Period', 'On Resign Period'), ('Absconded', 'Absconded')], default='Active', max_length=20)),
                ('on_break', models.BooleanField(default=False)),
                ('commitment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='agents',
            field=models.ManyToManyField(related_name='teams_as_agent', to='CallCenter_App.userprofile'),
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_as_leader', to='CallCenter_App.userprofile'),
        ),
        migrations.CreateModel(
            name='LeadTransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(auto_now_add=True)),
                ('transfer_time', models.TimeField(auto_now_add=True)),
                ('transfer_remark', models.TextField(blank=True, null=True)),
                ('disposition', models.CharField(choices=[('Fresh', 'Fresh'), ('Connected', 'Connected'), ('Not connected', 'Not connected')], default='Fresh', max_length=20)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_records', to='CallCenter_App.lead')),
                ('sub_disposition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_leads', to='CallCenter_App.subdisposition')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferred_leads_from', to='CallCenter_App.userprofile')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferred_leads_to', to='CallCenter_App.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='CallCenter_App.userprofile'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Pending', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='CallCenter_App.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='CallCenter_App.attendance')),
                ('break_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CallCenter_App.breaktype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CallCenter_App.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='CallCenter_App.userprofile'),
        ),
        migrations.CreateModel(
            name='AgentSalesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('commitment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_history', to='CallCenter_App.userprofile')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sales', to='CallCenter_App.userprofile')),
            ],
        ),
    ]
