# Generated by Django 5.0.6 on 2024-07-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CallCenter_App', '0003_alter_agentsaleshistory_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidcustomer',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
